name: Build-branch Deploy
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install pnpm
        run: npm i -g pnpm
      - name: install deps
        run: pnpm i
      - name: build
        run: pnpm prepublishOnly
      - name: prepare github publish
        run: node scripts/prepare-package-json.mjs
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./build
          publish_branch: build
